import Head from 'next/head'
import Image from 'next/image'
import { Inter, Open_Sans } from 'next/font/google'
import styles from '@/styles/Home.module.css';
import UploadSection from '@/comps/UploadSection';
import Plans from '@/comps/Plans';
import GetStarted from '@/comps/GetStarted';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={inter.className}>
      <Head>
        <title>PhotoSwift | Landing Page </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.maincover}`}>
        <div className={styles.main}>
          <div className={styles.herotext}>
            <h2>Combine all your photo memories in one place</h2>
            <p>Lets help you connect and share your memories with your family and friends</p>
            <button className={styles.button}>Get started</button>
          </div>
          {/* <Image src='/squat1.jpg' alt='hero' width={228} height={100}/> */}
          <div className={styles.heroimage}>
            <img src="/blue-lady.png" alt="hero image" className={styles.lady}/>
            <div className={styles.first}><span><img src="/sender.png" alt="picture icon" /></span> <p><b>John Addy</b> <br/>just liked your photo.</p></div>
            <div className={styles.sec}><span><img src="/status.png" alt="picture icon" /></span> <p><b>Victoria Sam</b> <br/>shared your photo. Check it out</p></div>
            <div className={styles.third}><span><img src="/user.png" alt="picture icon" /></span> <p><b>Cynthia Robinson</b><br/> commented on your profile picture</p></div>
          </div>
        </div>
      </main>
      <UploadSection/>
      <Plans/>
      <GetStarted/>
    </div>
  )
}
